In [1]:
import numpy as np

input_matrix = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36]
])

kernel = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

output_size = (input_matrix.shape[0] - kernel.shape[0]) // 1 + 1

output_matrix = np.zeros((output_size, output_size))


for i in range(output_size):
    for j in range(output_size):
        region = input_matrix[i:i + kernel.shape[0], j:j + kernel.shape[1]]
        output_matrix[i, j] = np.sum(region * kernel)

print("Input:")
print(input_matrix)

print("\Kernel:")
print(kernel)

print("\nOutput:")
print(output_matrix)

Input:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
\Kernel:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Output:
[[ 474.  519.  564.  609.]
 [ 744.  789.  834.  879.]
 [1014. 1059. 1104. 1149.]
 [1284. 1329. 1374. 1419.]]
