In [2]:
import numpy as np

input_matrix = np.array([
    [474, 519, 564, 609],
        [744, 789, 834, 879],
        [1014, 1059, 1104, 1149],
        [1284, 1329, 1374, 1419]
])

kernel = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

output_size = (input_matrix.shape[0] - kernel.shape[0]) // 1 + 1

output_matrix = np.zeros((output_size, output_size))


for i in range(output_size):
    for j in range(output_size):
        region = input_matrix[i:i + kernel.shape[0], j:j + kernel.shape[1]]
        output_matrix[i, j] = np.sum(region * kernel)

print("Input:")
print(input_matrix)

print("\Kernel:")
print(kernel)

print("\nOutput:")
print(output_matrix)

Input:
[[ 474  519  564  609]
 [ 744  789  834  879]
 [1014 1059 1104 1149]
 [1284 1329 1374 1419]]
\Kernel:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Output:
[[40635. 42660.]
 [52785. 54810.]]


In [6]:
import numpy as np

def full_convolution(input, kernel):
    input_height, input_width = input.shape
    kernel_height, kernel_width = kernel.shape
    output_height = input_height + kernel_height - 1
    output_width = input_width + kernel_width - 1

    output = np.zeros((output_height, output_width))

    for i in range(input_height):
        for j in range(input_width):
            for k in range(kernel_height):
                for l in range(kernel_width):
                    output[i + k, j + l] += input[i, j] * kernel[k, l]

    return output

dLdO2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

K2 = np.array([
    [1, 2],
    [3, 4]
])


output = full_convolution(dLdO2, K2)

print("Output matrix:")
print(output)

Output matrix:
[[ 1.  4.  7.  6.]
 [ 7. 23. 33. 24.]
 [19. 53. 63. 42.]
 [21. 52. 59. 36.]]
